# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

  # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
  providers:
    in_memory:
      memory: ~

    session_provider:
      id: session_provider

  firewalls:
    public:
      pattern: ^(/api/users)|(/api/users/auth)$
      methods: [POST]
      security: false

    logged_session:
      pattern: ^/api/(users|history|borrow|book)
      stateless: true
      simple_preauth:
        authenticator: user_authenticator
      provider: session_provider

  encoders:
    App\Entity\User:
      algorithm: bcrypt
      cost: 12