# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

        service_provider:
            id: service_provider

    firewalls:
        public:
            pattern: ^/hello$
            security: false

        api_key:
            # api key access for other microservices
            pattern: ~
            stateless: true
            simple_preauth:
                authenticator: service_authenticator
            provider: service_provider

