version: '2'

services:
  db:
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - bridge
  php:
    build: ./.docker/php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/application:cached
      - ./var/logs/symfony:/var/www/application/var/logs:cached
    links:
      - db
    networks:
      - bridge
  nginx:
    build: ./.docker/nginx
    ports:
      - "80:80"
    links:
      - php
    volumes_from:
      - php
    volumes:
      - ./var/logs/nginx/:/var/log/nginx:cached
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.24.0.1/16"
          gateway: "172.24.0.1"